### ISSUE TITLE
Can't get Anaconda (python) Virtual Environment name to display in bash prompt

### ISSUE THREAD

**Issue by alysivji** [arialdomartini/oh-my-git#102]
I can't get the Anaconda virtual environment name to display on the 2nd line of my bash prompt.

I tried to follow the fix for virtualenv from the README (replacing ```$VIRTUAL_ENV``` with ```$CONDA_PREFIX```), but that did not work.

If I can be pointed in the right direction, I can make the fix and create a pull request.

Thanks!

**Comment by alysivji** [comment]
I started using [Bash-it](https://github.com/Bash-it/bash-it) instead. Closing this issue. Thanks

**Comment by kevinrue** [comment]
Actually, I'm a fairly user of `oh-my-git` and just realized that I'm facing the issue described here.
I'll start digging, but any advice would be appreciated.
