### ISSUE TITLE
Some symbols are not displaying properly in VS Code

### ISSUE THREAD

**Issue by fajaryanw** [arialdomartini/oh-my-git#103]
I have just installed oh-my-git in [oh-my-zsh
](http://ohmyz.sh/) I am following [this](https://github.com/arialdomartini/oh-my-git#how-to-install-antigen)

In my terminal looks fine
![terminal zsh](https://cloud.githubusercontent.com/assets/6999559/23448755/6efc64dc-fe85-11e6-83a8-bac905662abe.png)

But in [Visual Studio Code](https://code.visualstudio.com/) Integrated Terminal, there are some symbols isn't displaying properly
![zsh vsc](https://cloud.githubusercontent.com/assets/6999559/23448836/e918c9d6-fe85-11e6-8e71-74890167e23d.png)
 
**P.S.**
**OS:** Ubuntu 16.04
**Font:** SourceCodePro+Powerline+Awesome Regular

**Comment by jay16213** [comment]
@fajaryanw , please change your setting to``"'SourceCodePro+Powerline+Awesome Regular'"``, 
you forgot the single quotes and that's why this error happened

**Comment by fajaryanw** [comment]
@jay16213 thanks, it works
