### ISSUE TITLE
git version 2.13.0 error when not in git directory

### ISSUE THREAD

**Issue by yifan** [arialdomartini/oh-my-git#110]
I just updated git with homebrew. The new git will print error message related to this commit:
https://github.com/git/git/commit/b1ef400eece473f83f39980c54f67e3e7d202538

Now I keep getting this `fatal: BUG: setup_git_env called without repository` message for every command and directory in my terminal.

**Comment by jawshooah** [comment]
I've reported the issue to the Git mailing list and a patch is in the works, as `BUG` assertions should never happen in the wild, but oh-my-git probably shouldn't be calling `git config --local` outside of a Git repository to begin with.

**Comment by massar** [comment]
Simply redirecting the error to /dev/null and at least it is not confusingly (as one might think it is the command you run, instead of the prompt :) ) popping up that error all the time.

diff:
```
diff --git a/base.sh b/base.sh
index 5be07b3..d49c573 100644
--- a/base.sh
+++ b/base.sh
@@ -49,7 +49,7 @@ function get_current_action () {
 }

 function build_prompt {
-    local enabled=`git config --local --get oh-my-git.enabled`
+    local enabled=`git config --local --get oh-my-git.enabled 2>/dev/null`
     if [[ ${enabled} == false ]]; then
         echo "${PSORG}"
         exit;
```


Also some wee little background from https://github.com/blog :
```
The last few versions of Git have cleaned up many corner cases around repository discovery and initialization. As a final step in that work, Git 2.13 introduced a new assertion to catch any cases that were missed. After being tested for months in development versions, this shouldn't trigger. But it's possible that you may see BUG: setup_git_env called without repository. If you do, please consider making a bug report. [source]
```
and other people are reporting issues as well:
https://www.spinics.net/lists/git/msg303775.html

**Comment by sw0x2A** [comment]
I think better solution is to simply drop `--local`. git-config will skip repo-level config if it is not in a repo and fatal is not triggered.

**Comment by Casyfill** [comment]
tried, but both suggestions didn't work for me.
do I need to reinstall the plugin somehow after changing the `base.sh`?

**Comment by florinpatrascu** [comment]
@Casyfill - for me it worked after reloading `~/.profile` HTH

**Comment by huxi** [comment]
Message changed from `fatal: BUG: setup_git_env called without repository` (2.13.1) to `fatal: --local can only be used inside a git repository` (2.13.2).

**Comment by cy4n** [comment]
there's additional value to removing the --local instead of skipping the error:
https://github.com/arialdomartini/oh-my-git/pull/109#issuecomment-311462105

**Comment by macropin** [comment]
Just hit this with the latest `Xcode 9.0` update which ships `git version 2.13.5 (Apple Git-94)`.

**Comment by macropin** [comment]
Looks like there is a PR for this #109

**Comment by arialdomartini** [comment]
@yifan,  @jawshooah, @massar, @sw0x2A,  @Casyfill, @florinpatrascu, @huxi, @macropin 

thank you very much to you all! I'm closing this issue, since #109, which fixed the problem, has been merged to master. Grazie mille!
