### ISSUE TITLE
Anitgen usage instructions are incorrect in ``README.md``

### ISSUE THREAD

**Issue by ortonomy** [arialdomartini/oh-my-git#116]
You use a hyphen in the antigen commands, which break and do not work. Should be:

# How to install antigen

antigen is a plugin manager for zsh. Installing antigen is straightforward:

```
cd ~ && git clone https://github.com/zsh-users/antigen.git .antigen 
```

Then, edit your .zshrc file including

```
source "$HOME/.antigen/antigen.zsh"

antigen use oh-my-zsh  // no hyphen needed
antigen bundle arialdomartini/oh-my-git // no hyphen needed
antigen theme arialdomartini/oh-my-git-themes oppa-lana-style

antigen apply // no hyphen needed
```

When you restart zsh, antigen will download and install all that's needed.

**Comment by arialdomartini** [comment]
Great, I just discovered I was using a very old Antigen version.
With version 2.2.1 I was able to reproduce the issue. I'm definitely going to fix it.
