### ISSUE TITLE
Windows bash

### ISSUE THREAD

**Issue by moonantonio** [arialdomartini/oh-my-git#137]
Hi,
Is it possible to implement it in git bash for windows?

**Comment by OmorFaruque-65** [comment]
Yeah, it would be great if it can be implemented with git bash on windows. 
Hope I will find the answer here cause I am desperately looking for a solution.

**Comment by MoonAntonio** [comment]
So far, I have only been able to use it in wsl with Fluent Terminal.

**Comment by loctran016** [comment]
I've tried this and it's working:
```zsh
cd c:/
git clone https://github.com/arialdomartini/oh-my-git.git
```
Add this line to `C:\Program Files\Git\etc\profile.d\git-prompt.sh`:
```sh
source c:/oh-my-git/prompt.sh
```
