### ISSUE TITLE
how remove time and username@hostname ?

### ISSUE THREAD

**Issue by MosqutitoLiu** [arialdomartini/oh-my-git#143]
can you help me please? tell me  how remove time and username@hostname ?

![截屏2021-06-17 上午11 00 52](https://user-images.githubusercontent.com/1235307/122324497-75303800-cf5b-11eb-8fac-85fa34d200e7.png)

**Comment by arialdomartini** [comment]
Hi!
You can edit `omg_second_line` which defaults to

```
: ${omg_second_line:=$PS1}
```

Just tell me if it works!

**Comment by MosqutitoLiu** [comment]
> Hi!
> You can edit `omg_second_line` which defaults to
> 
> ```
> : ${omg_second_line:=$PS1}
> ```
> 
> Just tell me if it works!

it doesn't work .

**Comment by arialdomartini** [comment]
My fault!
I’ll be far from the keyboard for a couple of days: I’ll give you a working answer as soon as back!

**Comment by arialdomartini** [comment]
My fault.
It's `RPROMPT`

Just add a 

```
RPROMPT="whatever"
```

The default value is:

```
%{$reset_color%}%T %{$fg_bold[white]%} %n@%m%{$reset_color%}
```
