### ISSUE TITLE
It does not support python virtualenvs properly

### ISSUE THREAD

**Issue by arialdomartini** [arialdomartini/oh-my-git#38]

**Comment by atav32** [comment]
+1

**Comment by arialdomartini** [comment]
Hi @atav32, hi @andreagrandi 

Would you please help me deciding how to fix this issue? Apparently, we all are interested in making oh-my-git compatible with python virtualenv.

I read a bit about how virtualenv injects the virtualev name into the prompt. Unfortunately, I discovered that the virtualenv's approach is pretty disappointing (see [Virtualenv's bin/activate is Doing It Wrong](https://gist.github.com/datagrok/2199506)): in short, the virtualenv script ```activate``` performs a

```
PS1="(`basename \"$VIRTUAL_ENV\"`)$PS1"
```
that is, it arrogantly prepends the virtualenv name to the current ```PS1```, leaving the user no opportunity to customise the output.
This means that with zsh the result is

![screen shot 2015-01-22 at 08 57 08](https://cloud.githubusercontent.com/assets/150719/5852306/b6630102-a214-11e4-9466-7440630db8f8.png)

while with bash no virtualenv name is displayed at all.
This sucks.

What I would like to obtain is a prompt with the virtualenv name injected in a position which may be freely customised by the theme.

@andreagrandi has submitted in the pull request https://github.com/arialdomartini/oh-my-git/pull/35 a possible solution.

I love it, but I feel that the oh-my-git script should be *python-agnostic*. The fact that the script is directly coupled to the ```$VIRTUAL_ENV``` is something I would like to improve.
For example, I'm not in the Ruby side, but I would not be surprised if something like virtualenv name injection in the prompt also exists in Ruby. I don't think that supporting all the languages and the possible combinations directly oh-my-git is a good idea (it would violate the SRP, wouldn't it?)
I'd prefer some more *pluggable* approach.

Hence, I came with another possible solution, which I submitted in the pull request https://github.com/arialdomartini/oh-my-git/pull/40 for bash, and in the PL https://github.com/arialdomartini/oh-my-git-themes/pull/2 for the zsh theme oppa-lana-style

I would love if you could help me reviewing the code and trying the feature. As far as I understand @andreagrandi is on the bash side, while @atav32 is a zsh lover.

For zsh both the repositories oh-my-git and oh-my-git-themes must be switched to the branch ```prompt-callback```, while for bash there's no need for oh-my-git-themes at all.

Please, feel free to decline, of course!
Cheers!

**Comment by atav32** [comment]
Haha sorry I'm also bash, but I'm excited to try out the fix

**Comment by andreagrandi** [comment]
Hi @arialdomartini ! I did some small changes to the PR I did for you and you can find my version here: https://github.com/andreagrandi/oh-my-git 

It still uses the "inject" approach, but it's not that bad... I mean: if no venv is available, no string is displayed in that place. I also changed the place where you display the venv information. Here is my output:

![oh_my_git_venv](https://cloud.githubusercontent.com/assets/636391/5949281/f525aa46-a743-11e4-9d68-ca104de5a4f5.png)

What do you think about?

**Comment by arialdomartini** [comment]
@andreagrandi, while I really liked the simplicity of your PL (way less code lines than mine!), I finally decided I didn't want to make oh-my-git python dependent, and I merged the pull request https://github.com/arialdomartini/oh-my-git/pull/40. I hope you don't mind too much!
