### ISSUE TITLE
Original prompt preserving fails... badly

### ISSUE THREAD

**Issue by viraptor** [arialdomartini/oh-my-git#43]
After loading oh-my-git via antigen, I get this in my prompt:

    $PROMPT_SUCCESS_COLOR~$reset_color $GIT_PROMPT_INFO$(git_prompt_info)$GIT_DIRTY_COLOR$(git_prompt_status) $reset_color$PROMPT_PROMPTᐅ$reset_color              14:38  viraptor@gumby

Doesn't seem right... My `.zshrc` is pretty simple:

    source $HOME/Projects/antigen/antigen.zsh

    antigen use oh-my-zsh

    antigen bundle git
    antigen bundle pip
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle arialdomartini/oh-my-git

    antigen theme muse
    antigen theme arialdomartini/oh-my-git-themes oppa-lana-style

    antigen apply

Once in the git directory, it works fine. It's the "normal" state that's messed up.

**Comment by arialdomartini** [comment]
Hi @viraptor 
I noticed that the use of `theme muse` together with `oh-my-git` can be the cause.

In fact, the prompt you get is exactly the one defined in https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/muse.zsh-theme#L16

Could you please try commenting the following line?

```
antigen theme muse
```

**Comment by viraptor** [comment]
That worked, thanks. I must've misunderstood the example - I expected the theme to revert to the previously set one outside of git repos.

**Comment by arialdomartini** [comment]
You are welcome!
