### ISSUE TITLE
Prompt prefix full computer name issue

### ISSUE THREAD

**Issue by jamez14** [arialdomartini/oh-my-git#46]
I'm wondering if this is something on my end or possibly a setting I can flip to help to "fix" this *issue*. As you can see in the image below, when I'm not in a git repo, the prefix of the repo is my full computer name along with my name followed by a $ sign. Although when I am in a Git repo, it works as expected. So for example, when in the root directory `~`, my prompt would look like: `Admins-MacBook-Pro:~ james.mosier$`. Is there a way I can manually remove this entire prefix? Or is it possibly an existing bug I could help to fix?

![screen shot 2015-02-03 at 9 00 28 am](https://cloud.githubusercontent.com/assets/2854919/6021554/a78e2e4e-ab84-11e4-9178-8b9a12d71e0d.png)

**Comment by arialdomartini** [comment]
Hi @jamez14 

Let me understand better.

For the sake of simplicity, let's call `ungit_prompt` the prompt you have when you are outside a git repo. When you are inside a git repo, the actual prompt is composed by two lines: the first one which we could call the `oh-my-git_prompt` and the `second_line`.

What you are saying is that the `ungit_prompt` is not equal to the `second_line`, aren't you?

Actually, both can be defined by using two variables in the `.bashrc` or in `.profile`

```
omg_ungit_prompt="whatever"
omg_second_line="whatever"
```


It's true, thou, that the default `second-line` is `\w • `, and this is confusing.

I think by default oh-my-git should preserve the original `PS1`. I prepared a the PL https://github.com/arialdomartini/oh-my-git/pull/52 which should fix the problem.


I'm very interested on your opinion about that.

**Comment by jamez14** [comment]
I think that makes the most sense. Also you're right that `ungit_prompt` is not equal to `second_line`. By preserving the original `PS1`, I find it easier (personally) to be able to make any adjustments to my `ungit_prompt` settings.

I've incorporated your PR into my `prompt.sh` pending the next release so I can have this locally now. Thanks for your help with this and for looking into it so quickly!

**Comment by arialdomartini** [comment]
Hi @jamez14 !
Thanks a lot! I'm merging the PR!
