### ISSUE TITLE
Patched font doesn't work with iTerm 2

### ISSUE THREAD

**Issue by kendall** [arialdomartini/oh-my-git#47]
![ohmygit](https://cloud.githubusercontent.com/assets/1251/6024665/e7f4967e-ab9a-11e4-9902-44d44ae2e1e2.png)

**Comment by arialdomartini** [comment]
Hi @kendall 

In my version of iTerm2 the font has to be set twice, both for **Regular Font** and for **Non ASCII Font**.
My current settings is this one

![screen shot 2015-02-03 at 17 57 46](https://cloud.githubusercontent.com/assets/150719/6024833/625d828a-abce-11e4-88ba-fa5b85acb1fd.png)

I wonder if your situation may depends on the **Non ASCII Font** part missing the font.

**Comment by kendall** [comment]
Meh! I'm an idiot. Of course that's it. Please close this so my stupidity is not so visible.

**Comment by arialdomartini** [comment]
@kendall ^_^   On the contrary, I think I'd better add this to the instructions, and thank you because it's actually a lack of information in the readme.

**Comment by arialdomartini** [comment]
I patched the readme. Thank you, @kendall !

**Comment by pdostal** [comment]
@kendall I spent also an hour by solving this 'issue' - don't worry :+1:
