### ISSUE TITLE
Looks bad

### ISSUE THREAD

**Issue by Sgiath** [arialdomartini/oh-my-git#49]
Hi, why my Terminal with git repository looks so bad? (arrow at the end of "git line"). Is it just because I've changed colors in my profile or there is some way how to fix it?
![oh-my-git](https://cloud.githubusercontent.com/assets/6009528/6031476/0b9bfe2c-ac00-11e4-898a-324a71be6cb5.png)

Thanks

**Comment by arialdomartini** [comment]
Hi @Sgiath 
Yes, it depends on the background color.
I'm working on a fix, which I will document in the readme. Stay tuned, I'll be pushing it in few hours.

**Comment by arialdomartini** [comment]
Hi @Sgiath 
The issue should be fixed. Please find a detailed description in the readme.
I hope this helps!

**Comment by Sgiath** [comment]
I have better fix for that :)
![oh-my-git](https://cloud.githubusercontent.com/assets/6009528/6039646/454c965e-ac69-11e4-8f80-37425181d04b.png)
In color palette set the first color (top-left corner) same as background color and this fix it ;)

**Comment by arialdomartini** [comment]
Great!
I'm adding this to te readme.

Anyway, this works as long as the background is taken from the 16 colors palette. With OS X Terminal, thou, the background can be choosed from a 16M palette, and this makes the problem harder.

I'm adding your solution in the documentation. Thanks, @Sgiath !

**Comment by krayon** [comment]
@arialdomartini 

I'm SURE I've missed something, but is there any reason you wouldn't just reset then set foreground to red again?

This appears to have the desired affect to me:
https://github.com/krayon/oh-my-git/tree/lastcharfix

**Comment by arialdomartini** [comment]
Ciao @krayon.
does it work with any background color? If so, I'll be happy to merge a pull request of yours!

**Comment by krayon** [comment]
@arialdomartini Sorry I missed your reply. It does work for me with any background colour in urxvt but I've not tried it in anything else. My only hesitation is that it seemed so obvious I assume there must be a reason no one else offered it :S

**Comment by krayon** [comment]
@arialdomartini As requested, I have created a PR ( #108 )
