### ISSUE TITLE
Number of stashes is always 1 (if not 0)

### ISSUE THREAD

**Issue by blueyed** [arialdomartini/oh-my-git#57]
The method used to get the number of stashes (https://github.com/arialdomartini/oh-my-git/blob/master/base.sh#L104) counts the lines in `.git/refs/stash`, but that is just the sha of the top stashed entry.

I am using `git stash list | wc -l` to get the numbers of stashes.

**Comment by arialdomartini** [comment]
Hi @blueyed 

You are right! I'm fixing it!
