### ISSUE TITLE
arrow size on OSX

### ISSUE THREAD

**Issue by kopipejst** [arialdomartini/oh-my-git#59]
![screen shot 2015-02-07 at 11 10 46 am](https://cloud.githubusercontent.com/assets/198219/6093589/16fba3a0-aeba-11e4-8589-5410f28bba86.png)

**Comment by arialdomartini** [comment]
Are you on iTerm2? 

is it possible that you selected different fonts or sizes in the 2 sections?

![screen shot 2015-02-10 at 13 02 39](https://cloud.githubusercontent.com/assets/150719/6126875/1d2a9a8e-b125-11e4-92cb-78b987db0179.png)

**Comment by kopipejst** [comment]
I'm using Terminal. my font size is 12

**Comment by arialdomartini** [comment]
Hi @kopipejst 
As far as I understand, you are using the same font, with the same size in both the sections.

Have you tried to experiment with other sizes? Is the problem the same no matter what the font size is?

**Comment by kopipejst** [comment]
![screen shot 2015-02-12 at 6 10 41 am](https://cloud.githubusercontent.com/assets/198219/6168877/07142382-b27e-11e4-9056-efff8ae68ef0.png)

problem is same with any font size

**Comment by sorin-ionescu** [comment]
You need to adjust vertical character spacing in the font dialogue.

**Comment by kopipejst** [comment]
@sorin-ionescu thanks
