### ISSUE TITLE
Missing explanation in documentation

### ISSUE THREAD

**Issue by albertorestifo** [arialdomartini/oh-my-git#61]
There is an explanation missing:

Why when I'm on a branch (`ember` in this case) I see the view like this:
![image](https://cloud.githubusercontent.com/assets/1037048/6149821/ab6d9e4a-b20b-11e4-9dfe-6e2a8a64b415.png)

The `--` are not showing me the progress against the origin and so on, but when on `master` I see the expected view:
![image](https://cloud.githubusercontent.com/assets/1037048/6149837/d40807f0-b20b-11e4-954d-0255d43b8cc5.png)

Can you explain this? I would suggest to add it to the documentation.

**Comment by arialdomartini** [comment]
Hi @albertorestifo 

I think I don't understand. Your branch `ember` is not tracking any remote branches. The symbol between the two `--` shows that the branch is local.

On the contrary, the branch `master` is tracking `origin/master`: then, oh-my-git displays the name of the remote (in your case `origin`) and the relative distance between your local branch and the tracked branch (in your case: `-1`).

I believe the first case was covered by this part of the documentation

It's true that the documentation doesn't explain the `local` symbol.

Is this info that you are suggesting to add to documentation?

Thank you very much for your feedback!

**Comment by albertorestifo** [comment]
Yes, exactly!

Oh ok, so my branch `ember` is being tracking locally. Perfect. I forgot to add a `-u` on the first push I did to the remote.

Very useful feedback!

**Comment by arialdomartini** [comment]
Fixed, thank you!
