### ISSUE TITLE
Updates on repo changes

### ISSUE THREAD

**Issue by arthur-nickless** [arialdomartini/oh-my-git#84]
This is probably a large request ( or not possible for a git prompt - I don't know )  but it would be cool if oh-my-git re-rendered/re-calculated anytime a file was changed, removed or added etc.

Oh-my-git is excellent but one of the problems I have with it is it not being a "live state" of the code you're working on, you have to call git status or run a terminal command for it to re-render/re-calculate itself.

Either way keep up the good work.

**Comment by NobbZ** [comment]
You can't live render the prompt. Neither bash nor zsh nor any other shell
I worked with allowed that, but simply hitting enter on the prompt gave me
a new up to date prompt.

arthur-nickless <notifications@github.com> schrieb am Di., 14.07.2015,
23:22:

**Comment by arthur-nickless** [comment]
[Closed]
Reason: It seems the prompts that oh-my-git run on unfortunatley do not support listening to files events.
