### ISSUE TITLE
Missing icons even after installing the fonts

### ISSUE THREAD

**Issue by SpikeShape** [arialdomartini/oh-my-git#90]
I still see weird icons although I followed the instructions and installed all the three fonts.

I already got it working on an OS X 10.10 Yosemite but now I am on El Capitan.

Are there ay reports of Oh My Git not working on OS X 10.11?

**Comment by darktiny** [comment]
You need this https://github.com/arialdomartini/oh-my-git/issues/37

**Comment by SpikeShape** [comment]
Thank you a lot! Gonna try that asap.
