### ISSUE TITLE
No prompt after Mac (El Capitan) install

### ISSUE THREAD

**Issue by cici** [arialdomartini/oh-my-git#98]
I used the one-liner and then opened a new window and sourced .profile.  I don't get a prompt at all:

| => source ~/.profile
-bash: total: No such file or directory
-bash: build_prompt: command not found

**Comment by cici** [comment]
For some reason, my $BASH_SOURCE is returning the entire directory listing, so that's why it is returning the word "total".  I made a change to prompt.sh and it works now.

**Comment by tweeres04** [comment]
Thanks, I got a similar issue and you helped me resolve it. I just removed the `DIR` variable and hard coded the path to my `base.sh` file on the next line.
